INSERT INTO STORE (id,CITY,STATE, STREET_NAME, STREET_NUMBER,
ZIP_CODE,CONTACT_PHONE,IMAGE_URL,LATITUDE,LONGITUDE,NAME) VALUES (9999,'city','state','stName','stNumber','zipCode','phone','',1,2,'test');

INSERT INTO PRODUCT (id,CATEGORY,CURRENCY,DESCRIPTION,IMAGE_URL,INVENTORY_STATUS,NAME,PRICE,STORE_ID) VALUES (9999,'category','€','descrip','','OUTOFSTOCK','test',1,9999);