---
name: Run Tests
on:
  pull_request:
    branches:
      - main
  push:
  
jobs:
  testBackend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: clear project
        run: mvn clean
        working-directory: ./backend
      - name: compile the project
        run: mvn compile
        working-directory: ./backend
      - name: run test case
        run: mvn test
        working-directory: ./backend
      - name: Build with Maven
        run: mvn clean install package 
        working-directory: ./backend

  testCypressFrontEnd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v3
        with:
          working-directory: ./frontend
          project: ./
          browser: chrome
          start: npm run start
          wait-on: "http://localhost:4200"